# Generated by Django 2.2.13 on 2020-08-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Placeholder title', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='Placeholder text'),
        ),
    ]
